package textSorterPackage;

import fileCreatorPackage.FileCreatorMain;

/**
 * Main class for text file sorter.
 * Consider changing UNSORTED_SORTED_FILE_NAME when using any custom file,
 * as it is currently set to fit the file that was generated by my file creator.
 *
 */


public class TextSorterMain {
    private static final String SORTED_FILE_NAME = "sorted.txt";
    private static final String UNSORTED_SORTED_FILE_NAME = FileCreatorMain.UNSORTED_FILE_NAME;

    /**
     * max size (in chars) of the temp files we use to split the large input file into.
     *
     *
     * I don't really believe in a method to auto-adjust max block size by getting info about the free memory we can use
     * (Runtime.getRuntime().totalMemory() and etc)
     * consider just tuning it by hand
     */
    private static final int MAX_BLOCK_SIZE = 50000000;

    public static void main(String[] args) {
        TextFileSorter sorter = new TextFileSorter(MAX_BLOCK_SIZE);
        sorter.sortFile(UNSORTED_SORTED_FILE_NAME, SORTED_FILE_NAME);
    }
}
